services:
  db:
    image: mysql:8.0
    container_name: mysql_javan
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - javan_data:/var/lib/mysql

volumes:
  javan_data:
